package PRO2;

public enum BaloonColor {
    RED, BLUE, GREEN, YELLOW, ORANGE, PURPLE, CYAN, MAGENTA,
    LIGHT_BLUE, DARK_GREEN, LIGHT_GREEN, DARK_RED, DARK_BLUE,
    LIGHT_PURPLE, DARK_PURPLE, LIGHT_YELLOW
}
